# Site settings
title: Hanapha
email: admin@hanapha.com
description: >
  Your daily source for beautiful home decoration inspiration, cozy living room ideas, and smart interior design solutions for every lifestyle.

url: "https://hanapha.com"
baseurl: "/"

timezone: Asia/Jakarta

future: false

default-image: logo.jpg
logo: logo.jpg

built-by: Hanapha

copyright:
  name: Hanapha
  link: "https://hanapha.com"

markdown: kramdown
permalink: /:title/

paginate: 12
paginate_path: /page:num/

include:
  - _pages

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap